name: dubinstracking
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - matplotlib
  - shapely
  - numpy
  - pyyaml
  - jupyterlab
  - scipy
  - pandas
  - pyvista
  - tqdm
  - pip:
    - pymavlink
    - cartopy
    - utm
